<div class="row">
    <div class="col-xs-4">
        Ashn nas
    </div>
    <div class="col-xs-4">
    Ashn nas
    </div>
    <div class="col-xs-4">
    Ashn nas
    </div>
</div>
<div class="row">
    <div class="col-xs-4">Ashn nas
    </div>
    <div class="col-xs-4">Ashn nas
    </div>
    <div class="col-xs-4">Ashn nas
    </div>
</div>
<div class="row">
    <div class="col-xs-4">Ashn nas
    </div>
    <div class="col-xs-4">Ashn nas
    </div>
    <div class="col-xs-4">Ashn nas
    </div>
</div>